version: '3'
services:

  #php
  ebanx_app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: digitalocean.com/php
    container_name: ebanx_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ebanx_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ebanx_app_network

  #nginx
  ebanx_nginx:
    image: nginx:alpine
    container_name: ebanx_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ebanx_app_network

  #mysql
  ebanx_mysql:
    image: mysql:5.7.22
    container_name: ebanx_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - ebanx_app_network

#networks
networks:
  ebanx_app_network:
    driver: bridge
    
#volumes
volumes:
  dbdata:
    driver: local